basePath: /api/v1/nakup
definitions:
  api.PurchaseRequest:
    properties:
      count:
        minimum: 1
        type: integer
      name:
        minLength: 3
        type: string
      price_per_item_cents:
        minimum: 0
        type: integer
      type:
        enum:
        - FOOD
        - DRINK
        - SNACK
        type: string
    required:
    - count
    - name
    - price_per_item_cents
    - type
    type: object
  api.PurchaseResponse:
    properties:
      count:
        type: integer
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      price_per_item_cents:
        type: integer
      type:
        $ref: '#/definitions/models.PurchaseType'
      updated_at:
        type: string
    type: object
  api.ReservationRequest:
    properties:
      col:
        minimum: 1
        type: integer
      room_id:
        type: string
      row:
        minimum: 1
        type: integer
      theater_id:
        type: string
      time_slot_id:
        type: string
      type:
        allOf:
        - $ref: '#/definitions/models.ReservationType'
        enum:
        - ONLINE
        - POS
    required:
    - col
    - room_id
    - row
    - theater_id
    - time_slot_id
    - type
    type: object
  api.ReservationResponse:
    properties:
      col:
        type: integer
      created_at:
        type: string
      id:
        type: string
      row:
        type: integer
      time_slot_id:
        type: string
      type:
        $ref: '#/definitions/models.ReservationType'
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  middleware.HttpError:
    properties:
      code:
        type: integer
      fields:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
  models.PurchaseType:
    enum:
    - FOOD
    - DRINK
    - SNACK
    type: string
    x-enum-varnames:
    - Food
    - Drink
    - Snack
  models.ReservationType:
    enum:
    - ONLINE
    - POS
    type: string
    x-enum-varnames:
    - Online
    - Pos
  request.PaginatedResponse:
    properties:
      data: {}
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
    type: object
host: localhost:8081
info:
  contact: {}
  description: API za upravljanje z kinodvoranami in njihovim sporedom
  title: Nakup API
  version: "1.0"
paths:
  /reservations:
    get:
      consumes:
      - application/json
      description: List reservations
      operationId: ReservationsList
      parameters:
      - default: 10
        description: Limit the number of responses
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset the first response
        in: query
        name: offset
        type: integer
      - description: Sort results
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/request.PaginatedResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/api.ReservationResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: List reservations
      tags:
      - reservations
    post:
      consumes:
      - application/json
      description: Create reservation
      operationId: ReservationsCreate
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.ReservationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReservationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: Create reservation
      tags:
      - reservations
  /reservations/{reservationID}:
    delete:
      consumes:
      - application/json
      description: Delete reservation
      operationId: ReservationsDelete
      parameters:
      - description: Reservation ID
        format: uuid
        in: path
        name: reservationID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: Delete reservation
      tags:
      - reservations
    get:
      consumes:
      - application/json
      description: Show reservation
      operationId: ReservationsShow
      parameters:
      - description: Reservation ID
        format: uuid
        in: path
        name: reservationID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReservationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: Show reservation
      tags:
      - reservations
    put:
      consumes:
      - application/json
      description: Update reservation
      operationId: ReservationsUpdate
      parameters:
      - description: Reservation ID
        format: uuid
        in: path
        name: reservationID
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.ReservationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReservationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: Update reservation
      tags:
      - reservations
  /reservations/{reservationID}/purchases:
    get:
      consumes:
      - application/json
      description: List purchases
      operationId: PurchasesList
      parameters:
      - description: Reservation ID
        format: uuid
        in: path
        name: reservationID
        required: true
        type: string
      - default: 10
        description: Limit the number of responses
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset the first response
        in: query
        name: offset
        type: integer
      - description: Sort results
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/request.PaginatedResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/api.PurchaseResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: List purchases
      tags:
      - purchases
    post:
      consumes:
      - application/json
      description: Create purchase
      operationId: PurchasesCreate
      parameters:
      - description: Reservation ID
        format: uuid
        in: path
        name: reservationID
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.PurchaseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.PurchaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: Create purchase
      tags:
      - purchases
  /reservations/{reservationID}/purchases/{purchaseID}:
    delete:
      consumes:
      - application/json
      description: Delete purchase
      operationId: PurchasesDelete
      parameters:
      - description: Reservation ID
        format: uuid
        in: path
        name: reservationID
        required: true
        type: string
      - description: Purchase ID
        format: uuid
        in: path
        name: purchaseID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: Delete purchase
      tags:
      - purchases
    get:
      consumes:
      - application/json
      description: Show purchase
      operationId: PurchasesShow
      parameters:
      - description: Reservation ID
        format: uuid
        in: path
        name: reservationID
        required: true
        type: string
      - description: Purchase ID
        format: uuid
        in: path
        name: purchaseID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.PurchaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: Show purchase
      tags:
      - purchases
    put:
      consumes:
      - application/json
      description: Update purchase
      operationId: PurchasesUpdate
      parameters:
      - description: Reservation ID
        format: uuid
        in: path
        name: reservationID
        required: true
        type: string
      - description: Purchase ID
        format: uuid
        in: path
        name: purchaseID
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.PurchaseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.PurchaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: Update purchase
      tags:
      - purchases
  /reservations/my:
    get:
      consumes:
      - application/json
      description: List reservations for the currently authenticated user
      operationId: MyReservationsList
      parameters:
      - default: 10
        description: Limit the number of responses
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset the first response
        in: query
        name: offset
        type: integer
      - description: Sort results
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/request.PaginatedResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/api.ReservationResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/middleware.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.HttpError'
      summary: List my reservations
      tags:
      - reservations
swagger: "2.0"
