services:

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nakup
    volumes:
      - nakup-pgdata:/var/lib/postgresql/data 
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 10s
      retries: 5

  nakup:
    ports:
      - "8081:8081"
    build: .
    depends_on:
      - db
    environment:
      - LOG_LEVEL=DEBUG
      - TZ=
      - POSTGRES_IP=db
      - POSTGRES_PORT=5433
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE_NAME=nakup
      - POSTGRES_TEST_DATABASE_NAME=nakup_test

volumes:
  nakup-pgdata: