services:

  nakup-db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nakup
    volumes:
      - nakup-pgdata:/var/lib/postgresql/data 
    ports:
      - 5442:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 10s
      retries: 5

  nakup:
    ports:
      - "8081:8081"
    restart: always
    build: .
    depends_on:
      nakup-db:
        condition: service_healthy
    environment:
      - LOG_LEVEL=DEBUG
      - TZ=
      - POSTGRES_IP=nakup-db
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE_NAME=nakup
      - POSTGRES_TEST_DATABASE_NAME=nakup_test
      - SPORED_HOST=localhost:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthcheck"]
      interval: 3s
      timeout: 10s
      retries: 5

volumes:
  nakup-pgdata: